In [1]:
for epoch in range(epochs):
    for x_batch, y_batch in data:
        train()

NameError: name 'epochs' is not defined

In [9]:
features = [1,2,3,4]
labels = [0,0,1,1]

data = features, labels

In [10]:
for x,y in data:
    print(x)
    print(y)

ValueError: too many values to unpack (expected 2)

In [12]:
for x, y in zip(features,labels):
    print(x,y)

1 0
2 0
3 1
4 1

In [15]:
import torch 
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import pandas as pd

In [23]:
class CustomDataset(Dataset): 
    def __init__(self):#constructer : __something__ is called automatically from python
        pass
    def __getitem__(self, index): #function ex. to index the list(iterator) //getitem standard in python
        pass
    def __len__(self): # len(dataset)
        pass

In [27]:
dataset_path = "https://people.sc.fsu.edu/~jburkardt/data/csv/homes.csv"

In [44]:
houses = pd.read_csv(dataset_path)

In [45]:
houses

,Sell,"""List""","""Living""","""Rooms""","""Beds""","""Baths""","""Age""","""Acres""","""Taxes"""
0,142,160,28,10,5,3,60,0.28,3167
1,175,180,18,8,4,1,12,0.43,4033
2,129,132,13,6,3,1,41,0.33,1471
3,138,140,17,7,3,1,22,0.46,3204
4,232,240,25,8,4,3,5,2.05,3613
5,135,140,18,7,4,3,9,0.57,3028
6,150,160,20,8,4,3,18,4.00,3131
7,207,225,22,8,4,2,16,2.22,5158
8,271,285,30,10,5,2,30,0.53,5702
9,89,90,10,5,3,1,43,0.30,2054
10,153,157,22,8,3,3,18,0.38,4127
11,87,90,16,7,3,1,50,0.65,1445
12,234,238,25,8,4,2,2,1.61,2087
13,106,116,20,8,4,1,13,0.22,2818
14,175,180,22,8,4,2,15,2.06,3917
15,165,170,17,8,4,2,33,0.46,2220
16,166,170,23,9,4,2,37,0.27,3498
17,136,140,19,7,3,1,22,0.63,3607
18,148,160,17,7,3,2,13,0.36,3648
19,151,153,19,8,4,2,24,0.34,3561
20,180,190,24,9,4,2,10,1.55,4681
21,293,305,26,8,4,3,6,0.46,7088
22,167,170,20,9,4,2,46,0.46,3482
23,190,193,22,9,5,2,37,0.48,3920
24,184,190,21,9,5,2,27,1.30,4162
25,157,165,20,8,4,2,7,0.30,3785
26,110,115,16,8,4,1,26,0.29,3103
27,135,145,18,7,4,1,35,0.43,3363
28,567,625,64,11,4,4,4,0.85,12192
29,180,185,20,8,4,2,11,1.00,3831
30,183,188,17,7,3,2,16,3.00,3564
31,185,193,20,9,3,2,56,6.49,3765
32,152,155,17,8,4,1,33,0.70,3361
33,148,153,13,6,3,2,22,0.39,3950
34,152,159,15,7,3,1,25,0.59,3055
35,146,150,16,7,3,1,31,0.36,2950
36,170,190,24,10,3,2,33,0.57,3346
37,127,130,20,8,4,1,65,0.40,3334
38,265,270,36,10,6,3,33,1.20,5853
39,157,163,18,8,4,2,12,1.13,3982
40,128,135,17,9,4,1,25,0.52,3374
41,110,120,15,8,4,2,11,0.59,3119
42,123,130,18,8,4,2,43,0.39,3268
43,212,230,39,12,5,3,202,4.29,3648
44,145,145,18,8,4,2,44,0.22,2783
45,129,135,10,6,3,1,15,1.00,2438
46,143,145,21,7,4,2,10,1.20,3529
47,247,252,29,9,4,2,4,1.25,4626
48,111,120,15,8,3,1,97,1.11,3205
49,133,145,26,7,3,1,42,0.36,3059

In [ ]:
print('Above 152',(houses.Sell.values > 152).sum())  #to get the array form from list // above 152 
print('Below 152',(houses.Sell.values <= 152).sum())

overwrite python class

In [25]:
dir(trial) # all function we can call with this particalar name // we can overide them

['__add__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_is_protocol']

In [46]:
class HouseDataset(Dataset):
    def __init__(self, csv_path, budget = 152):
        df = pd.read_csv(csv_path)
        df.columns = [x.replace('"',"").replace(" ","") for x in df.columns]
        columns = ['Living','Rooms','Beds','Baths','Age','Acres','Taxes']
        self.features = df[columns].values
        self.labels = (df.Sell.values <= budget).astype("int") #make true and false in 1 or 0
        self.n_samples = len(self.features)
    def __getitem__(self, index):
        return self.features[index], self.labels[index]
    def __len__(self):
        return self.n_samples

In [47]:
trial = HouseDataset(dataset_path,budget =152)

In [48]:
trialloader = DataLoader(dataset=trial, batch_size=3, shuffle=True)

In [53]:
dir(trialloader)

['_DataLoader__initialized',
 '_DataLoader__multiprocessing_context',
 '_IterableDataset_len_called',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_auto_collation',
 '_dataset_kind',
 '_get_iterator',
 '_index_sampler',
 '_is_protocol',
 '_iterator',
 'batch_sampler',
 'batch_size',
 'check_worker_number_rationality',
 'collate_fn',
 'dataset',
 'drop_last',
 'generator',
 'multiprocessing_context',
 'num_workers',
 'persistent_workers',
 'pin_memory',
 'prefetch_factor',
 'sampler',
 'timeout',
 'worker_init_fn']

In [54]:
a = [1,2,3,4,5,6,7,8,9,10]

In [55]:
a = range(1,11) #range is itereter knows where item is
# not loading all data in memory

In [56]:
a

range(1, 11)

In [57]:
for x in range(1,11):
    print(x)

1
2
3
4
5
6
7
8
9
10

In [50]:
dataiter = iter(trialloader)

In [51]:
dataiter.next() #give us one batch

[tensor([[1.8000e+01, 8.0000e+00, 4.0000e+00, 2.0000e+00, 1.2000e+01, 1.1300e+00,
          3.9820e+03],
         [1.7000e+01, 7.0000e+00, 3.0000e+00, 1.0000e+00, 2.2000e+01, 4.6000e-01,
          3.2040e+03],
         [1.3000e+01, 6.0000e+00, 3.0000e+00, 1.0000e+00, 4.1000e+01, 3.3000e-01,
          1.4710e+03]], dtype=torch.float64),
 tensor([0, 1, 1])]

# Images

In [58]:
from torchvision import datasets, transforms

In [59]:
'''
root
|_class1
    |_xxx.png
|_class2
    |_xxx.png
'''

'\nroot\n|_class1\n    |_xxx.png\n|_class2\n    |_xxx.png\n'

In [62]:
# .DS_Store sometimes counts as extra class
# rm .DS_Store to remove it

In [ ]:
root_dir = "example_dataset"

In [64]:
train_transforms = 

test_transforms =

SyntaxError: invalid syntax (<ipython-input-64-9872967fb17b>, line 1)

In [65]:
train_data = datasets.ImageFolder(root_dir + '/train', transforms = train_transforms)
train_loader =

NameError: name 'root_dir' is not defined